# Generated by Django 4.0.3 on 2022-07-27 13:08

import batch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batch_code', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(default=10000)),
                ('course_validity', models.DateField(default='2022-07-26')),
                ('image', models.ImageField(blank=True, null=True, upload_to='batch/')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('batch_code', models.IntegerField(default=2201)),
                ('subject_code', models.IntegerField(default=220101)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(null=True, upload_to='studymaterial/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('notif_type', models.CharField(choices=[('Announcement', 'Announcement'), ('Live Classes', 'Live Classes'), ('New Video', 'New Video')], default='New Video', max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('material', models.FileField(null=True, upload_to='studymaterial/', verbose_name='')),
                ('batch_code', models.IntegerField(default=2201)),
                ('subject_code', models.IntegerField(default=220101)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_code', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('batch_code', models.IntegerField(default=2201)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=batch.models.nameFile)),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('batch_codes', models.ManyToManyField(to='batch.batches')),
            ],
        ),
    ]
