# Generated by Django 4.0.3 on 2022-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_start', models.DateTimeField()),
                ('batch_code', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=20)),
                ('timing', models.TimeField()),
            ],
        ),
    ]
