# Generated by Django 4.0.3 on 2022-08-15 15:56

import batch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=batch.models.nameBatch),
        ),
    ]
