# Generated by Django 4.0.3 on 2022-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='course_code',
        ),
        migrations.AddField(
            model_name='batches',
            name='material_codes',
            field=models.ManyToManyField(to='batch.studymaterial'),
        ),
    ]
