# Generated by Django 4.0.3 on 2022-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_remove_studymaterial_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='course_codes',
        ),
        migrations.RemoveField(
            model_name='batches',
            name='material_codes',
        ),
        migrations.AddField(
            model_name='courses',
            name='batch_code',
            field=models.IntegerField(default=220101),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='batch_code',
            field=models.IntegerField(default=220101),
        ),
    ]
