# Generated by Django 4.0.3 on 2022-05-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
