# Generated by Django 4.0.3 on 2022-08-31 11:22

import batch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='batch_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=batch.models.nameFile),
        ),
    ]
