# Generated by Django 4.0.3 on 2022-07-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_remove_batches_course_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
