# Generated by Django 4.0.3 on 2022-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
