# Generated by Django 4.0.3 on 2022-08-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_batches_batch_code_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
