# Generated by Django 4.0.3 on 2022-07-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_courses_tumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='tumbnail',
        ),
    ]
