# Generated by Django 4.0.3 on 2022-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_alter_subjects_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch_codes',
            field=models.ManyToManyField(blank=True, null=True, to='batch.batches'),
        ),
    ]
