# Generated by Django 4.0.3 on 2022-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('notif_type', models.CharField(choices=[('A', 'Announcement'), ('B', 'Live Classes'), ('C', 'New Video')], default='C', max_length=2)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
