# Generated by Django 4.0.3 on 2022-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Live Classes', 'Live Classes'), ('New Video', 'New Video')], default='New Video', max_length=50),
        ),
    ]
