# Generated by Django 4.0.3 on 2022-05-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_profile_password'),
        ('batch', '0008_alter_notification_desc_and_more'),
    ]

    operations = [
    ]
