# Generated by Django 4.0.3 on 2022-06-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0009_merge_20220515_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(null=True, upload_to='studymaterial/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material',
            field=models.ManyToManyField(to='batch.material'),
        ),
    ]
