# Generated by Django 4.0.3 on 2022-06-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0010_story_story_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story_media',
            name='story',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='Story_Media',
        ),
    ]
