# Generated by Django 4.0.3 on 2022-06-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0010_material_remove_studymaterial_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material',
            field=models.FileField(null=True, upload_to='studymaterial/', verbose_name=''),
        ),
    ]
