# Generated by Django 4.0.3 on 2022-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0012_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
