# Generated by Django 4.0.3 on 2022-06-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0014_task_taskimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskimage',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
