# Generated by Django 4.0.3 on 2022-06-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0015_image_remove_taskimage_task_delete_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
