# Generated by Django 4.0.3 on 2022-06-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0011_remove_studymaterial_material_studymaterial_material'),
        ('batch', '0016_delete_image'),
    ]

    operations = [
    ]
